application: gae-last-across-the-finish-line
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

builtins:
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
